### SIGN UP
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "nickname": "joana", 
    "password": "1234567"
}
### LOGIN
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "nickname": "lauraamancio", 
    "password": "1234567"
}
### CREATE POLL
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMjQ3ODg5LTcxMDctNDM2YS1iNWIxLTM0MTYzYzM1ZGQwOSIsImlhdCI6MTY1OTk3MDQxMX0.gdNSqxJboOubL94rrpSczShnThLWIzaM6AIjkOrI7UA
@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNhMjg4ZWY2LTAyNWQtNDQ3ZC1hMzVmLTcwNjU1ZTUzZTU0MSIsImlhdCI6MTY1OTk2OTgwMX0.rhgP5zx8AxG0z4xB61iws5bDvp6A0GBUuL_QwRoyFnw
POST http://localhost:3003/polls
Content-Type: application/json
authorization: {{token}}

{
    "title": "jesus me ajuda", 
    "start_date": "16/08/2022",
    "end_date": "16/08/2022"
}
### ANSWER POLL
POST http://localhost:3003/polls/693a0c4e-ff40-4f70-8b35-3ba9c0f3a309
Content-Type: application/json
authorization: {{token}}

{
    "answer": "CONCORDO PARCIALMENTE"
}
### EDIT POLL
PUT http://localhost:3003/polls/2356ed56-0187-4185-9a82-a16bbdbd0d4f
Content-Type: application/json
authorization: {{token}}

{
    "start_date": "09/08/2022"
}
### DELETE POLL
DELETE  http://localhost:3003/poll/2356ed56-0187-4185-9a82-a16bbdbd0d4f
authorization: {{token}}

### GET ALL POLLS
GET http://localhost:3003/polls
authorization: {{token}}

### GET VOTES
GET http://localhost:3003/polls/votes/7866d555-73ed-453e-be1b-748327f6e63f
authorization: {{token}}

### GET POLL BY ID
GET http://localhost:3003/polls/eb3d83ed-f8b5-4e3f-a911-1e64eca59197
authorization: {{token}}
###
DELETE  http://localhost:3003/polls/answer/6a0e794e-6c6f-4d56-ae1e-f15042f89747
authorization: {{tokenAdmin}}